/* soapServer.c
   Generated by gSOAP 2.8.27 from oph_wsdl.h

gSOAP XML Web services tools
Copyright (C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.27 2016-01-26 17:34:35 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "oph:ophExecuteMain"))
		return soap_serve_oph__ophExecuteMain(soap);
	if (!soap_match_tag(soap, soap->tag, "oph:oph-notify"))
		return soap_serve_oph__oph_notify(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_oph__ophExecuteMain(struct soap *soap)
{	struct oph__ophExecuteMain soap_tmp_oph__ophExecuteMain;
	struct oph__ophResponse ophExecuteMainResponse;
	soap_default_oph__ophResponse(soap, &ophExecuteMainResponse);
	soap_default_oph__ophExecuteMain(soap, &soap_tmp_oph__ophExecuteMain);
	if (!soap_get_oph__ophExecuteMain(soap, &soap_tmp_oph__ophExecuteMain, "oph:ophExecuteMain", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = oph__ophExecuteMain(soap, soap_tmp_oph__ophExecuteMain.ophExecuteMainRequest, &ophExecuteMainResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_oph__ophResponse(soap, &ophExecuteMainResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_oph__ophResponse(soap, &ophExecuteMainResponse, "oph:ophResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_oph__ophResponse(soap, &ophExecuteMainResponse, "oph:ophResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_oph__oph_notify(struct soap *soap)
{	struct oph__oph_notify soap_tmp_oph__oph_notify;
	struct oph__oph_notifyResponse soap_tmp_oph__oph_notifyResponse;
	long soap_tmp_xsd__int;
	soap_default_oph__oph_notifyResponse(soap, &soap_tmp_oph__oph_notifyResponse);
	soap_default_xsd__int(soap, &soap_tmp_xsd__int);
	soap_tmp_oph__oph_notifyResponse.oph_notify_response = &soap_tmp_xsd__int;
	soap_default_oph__oph_notify(soap, &soap_tmp_oph__oph_notify);
	if (!soap_get_oph__oph_notify(soap, &soap_tmp_oph__oph_notify, "oph:oph-notify", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = oph__oph_notify(soap, soap_tmp_oph__oph_notify.oph_notify_data, soap_tmp_oph__oph_notify.oph_notify_json, soap_tmp_oph__oph_notifyResponse.oph_notify_response);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_oph__oph_notifyResponse(soap, &soap_tmp_oph__oph_notifyResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_oph__oph_notifyResponse(soap, &soap_tmp_oph__oph_notifyResponse, "oph:oph-notifyResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_oph__oph_notifyResponse(soap, &soap_tmp_oph__oph_notifyResponse, "oph:oph-notifyResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
